apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack
    receivers:
      - uid: slack
        type: slack
        settings:
          recipient: ${SLCAK_CHANNEL}
          token: ${SLACK_TOKEN}  # format: xoxb-...
        disableResolveMessage: false
