{
 "title": "cadvisor-exporter",
 "description": "Simple exporter for cadvisor only",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(up{job=\"cadvisor\"},env)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", env=\"$env\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{env=~\"$env\",name=~\"$container\",name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$env\",name=~\"$container\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{env=~\"$env\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{env=~\"$env\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{env=~\"$env\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{env=~\"$env\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}